name: My CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Your build steps here...

  deploy:
    runs-on: ubuntu-latest
    steps:
      # Your deploy steps here...

  # Ignore running tests based on a specific condition
  tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      name: Skip Tests
      run: echo "Tests are skipped for this workflow run."

# Other jobs can go here...
